---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ django_project_name }}.conf
            backup=yes

- name: Re-read the Supervisor config files
  supervisorctl: name={{ django_project_name }} state=present

- name: Restart Supervisor
  supervisorctl: name={{ django_project_name }} state=restarted
