---

- name: restart application
  supervisorctl: name={{ django_project_name }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded
